-- Enable Row Level Security (optional but good practice, though we might rely on service role key for simplicity in demo if we just use server-side)
-- For this demo, we will largely rely on the server-side client with the Service Role Key or Anon Key, 
-- but since the app handles auth internally, we just need the tables.

-- Users Table
create table if not exists users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  first_name text,
  last_name text,
  role text default 'reader',
  is_setup_complete integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Board Store Table
create table if not exists board_store (
  id bigint generated by default as identity primary key,
  data text
);

-- Initialize Board Store if empty
insert into board_store (id, data)
select 1, '{"projectName":"Ananke","workflows":[{"id":1,"title":"To Do","color":"#ef4444","tasks":[]},{"id":2,"title":"In Progress","color":"#f97316","tasks":[]},{"id":3,"title":"To Test","color":"#3b82f6","tasks":[]},{"id":4,"title":"Done","color":"#22c55e","tasks":[]}],"tags":[]}'
where not exists (select 1 from board_store where id = 1);
